### PR TITLE
Repo Improvements

### PR DESCRIPTION
**Pull request by AstroSquared**
- remove info from `README.md` saying the CI is not setup as `.github/workflows/build.yml` exists
- along with that, fixed the CI watching the wrong branch (`main` and not `master`) for changes
- improve the `.gitignore` file to remove `gradlew` and `gradlew.bat`, along with `.idea/discord.xml`
if there are any issue with this lmk

### CODE REVIEW

**Comment by AstroSquared** [comment]
on the topic of adding more files to `.gitignore`, should we ignore the entire directory? IntelliJ Idea generates all the files there on project import anyways. i'll make this a draft PR til i get a response

**Comment by RedVortexDev** [comment]
simply rename the branch to main smh

**Comment by AstroSquared** [comment]
that's the stupid solution xddddd much better to fix the CI

> simply rename the branch to main smh

**Comment by UserUNP** [comment]
Hello

**Comment by AstroSquared** [comment]
Hi

**Comment by infernostars** [comment]
> on the topic of adding more files to `.gitignore`, should we ignore the entire directory? IntelliJ Idea generates all the files there on project import anyways. i'll make this a draft PR til i get a response

you should be good, yeah - just make sure to edit because project rename

**Comment by akarahdev** [comment]
lgtm
@infernostars thoughts?

**Comment by infernostars** [comment]
lgtm

**Pull request merged**
